title: "Newsletter Pulse"
description: "Curated & Automated Gmail Newsletter Archive"
baseurl: "/daily-newsletters"
url: "https://vampcoder.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 12
paginate_path: "/page:num/"

